# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Feature"
  description: A feature to be used inside a section.
  icon: add_link
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  url:
  title:
  text:
  feature_color:
  image:
    path:
    feature_image_width:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  url: /
  title: A title
  text: Some text
  feature_color: "#FFF"
  image: 
    path: https://placekitten.com/50/50
    feature_image_width:
  
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    label: Title
    comment: The title for the feature.
    type: text
  text:
    label: Text
    comment: The main text content of the feature.
    type: markdown
  url:
    label: Url
    comment: The url of the page to link to.
    type: url
  path:
    label: Image Path
    comment: Link the path to your image.
    type: image
  feature_color:
    label: Link Color
    comment: Specify a color here for the feature text fields. Will default to global link color otherwise.
    type: color
  feature_image_width:
    label: Image Width
    comment: Specify a max-width for your image.
    type: number

